FROM haproxy:2.8-dev2

# Working directory 
WORKDIR /etc/haproxy

# Copy configuration file, pem certificate and HAProxy logs
COPY Deployment/full.pem /usr/local/etc/haproxy/full.pem
COPY Deployment/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg