version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    container_name: postgres
    volumes:
      - ../db-data:/data/postgres     # Do not version database mount place
    ports:
      - "5432:5432"
  db_management:
    build:
      context: .
      dockerfile: Dockerfile.DbManagement
    container_name: db-manager
    depends_on:
      - postgres
    network_mode: "host"
    ports:
      - "5000:5000"
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.Apache
    container_name: webserver
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"