FROM golang:1.19 AS builder

WORKDIR /main

COPY PublicStock .

RUN go mod init main && \
    go get -u github.com/gin-gonic/gin && \
    go get -u github.com/gin-contrib/cors && \
    go build - o app .

FROM alpine:3.17.2

WORKDIR /root/

COPY --from=builder /main/app ./

CMD ./app