FROM golang:1.19 AS builder

WORKDIR /main

COPY PublicStock .

RUN go build -o app . && \
    chmod +x app 

FROM alpine:3.17.2

WORKDIR /root/

COPY --from=builder /main/app ./

RUN apk add libc6-compat

CMD ./app