FROM python:3.9.16

WORKDIR /manager

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../DbManagement/* .

ENV FLASK_APP=app.py

CMD python population.py; python -m flask run --host=127.0.0.1